<!--
 * @Author: zengjing
 * @Date: 2024-10-29 16:25:18
 * @LastEditTime: 2024-12-19 16:26:44
 * @FilePath: \xsqdc:\Users\29737\Desktop\muckAbout\src\views\Python\ImageRename\components\instructions.vue
 * @Description: 
-->
<template>
  <MdPreview
    :editorId="id"
    :modelValue="decode(text)"
    :codeTheme="appStore.codeTheme"
    :theme="appStore.theme"
    :previewTheme="appStore.previewTheme"
    :codeFoldable="appStore.codeFoldable"
    :autoFoldThreshold="appStore.autoFoldThreshold"
  />
</template>
<script setup>
import { MdPreview, MdCatalog } from "md-editor-v3";
import { encode, decode } from "js-base64";
import { useAppStore } from "@/stores/app";
const appStore = useAppStore();
const id = "preview-only";
const text = ref(
  "IyMjIOaPj+i/sO+8miDmraTohJrmnKznlKjkuo7mibnph4/ph43lkb3lkI3mjIflrprnm67lvZXkuK3nmoTlm77niYfmlofku7bvvIzmlK/mjIHoh6rlrprkuYnmlofku7bmianlsZXlkI3lkozot6/lvoQKYGBgbGFuZ3VhZ2UKaW1wb3J0IG9zCmltcG9ydCBzaHV0aWwKaW1wb3J0IHRraW50ZXIgYXMgdGsKZnJvbSB0a2ludGVyIGltcG9ydCBmaWxlZGlhbG9nCiMg6YeN5ZCN5paH5Lu25ZCN56ewCmRlZiByZW5hbWVfaW1hZ2VzKGRpcmVjdG9yeSwgZXh0ZW5zaW9uPSJwbmciKQogICAgdHJ5OgogICAgICAgIGZpbGVzID0gb3MubGlzdGRpcihkaXJlY3RvcnkpCiAgICAgICAgZm9yIGksIGZpbGVuYW1lIGluIGVudW1lcmF0ZShmaWxlcyk6CiAgICAgICAgICAgIG5ld05hbWU9ZmlsZW5hbWUuc3BsaXQoIi4iKVswXQogICAgICAgICAgICBwcmludChmIlByb2Nlc3NpbmcgbmV3TmFtZSA6IHtuZXdOYW1lfS4uLntmaWxlbmFtZS5zcGxpdCgiLiIpLl9fbGVuX18oKX0iKQogICAgICAgICAgICBpZiBmaWxlbmFtZS5lbmRzd2l0aChmIi57ZXh0ZW5zaW9ufSIpIGFuZCBmaWxlbmFtZS5zcGxpdCgiLiIpLl9fbGVuX18oKSA9PSAyOgogICAgICAgICAgICAgICAgbmFtZT0i6IOM5pmvIgogICAgICAgICAgICAgICAgdGFyZ2V0TmFtZT0iYWRtaW4iCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgIG5ld05hbWU9bmV3TmFtZS5yZXBsYWNlKG5hbWUsIHRhcmdldE5hbWUpCiAgICAgICAgICAgICAgICBuZXdOYW1lPW5ld05hbWUucmVwbGFjZSgiQDJ4IiwgIi1kb3VibGUiKQogICAgICAgICAgICAgICAgbmV3TmFtZT1uZXdOYW1lLnJlcGxhY2UoIkAzeCIsICItdHJpcGxlIikKICAgICAgICAgICAgCiAgICAgICAgICAgICAgICBuZXdfZmlsZW5hbWUgPSBmIntuZXdOYW1lfS57ZXh0ZW5zaW9ufSIKICAgICAgICAgICAgICAgICMg6LCD55So5Ye95pWw5aSN5Yi25bm26YeN5ZG95ZCN5Zu+54mHIOWQiOW5tui3r+W+hOWSjOWQjeWtlwogICAgICAgICAgICAgICAgb2xkX3BhdGggPSBvcy5wYXRoLmpvaW4oZGlyZWN0b3J5LCBmaWxlbmFtZSkKICAgICAgICAgICAgICAgIG5ld19wYXRoID0gb3MucGF0aC5qb2luKGRpcmVjdG9yeSwgbmV3X2ZpbGVuYW1lKQoKICAgICAgICAgICAgICAgICMgb3MucmVuYW1lKG9sZF9wYXRoLCBuZXdfcGF0aCkKICAgICAgICAgICAgICAgICMg6LCD55Soc2h1dGlsLmNvcHkoKeWHveaVsOWkjeWItuWbvueJhwogICAgICAgICAgICAgICAgc2h1dGlsLmNvcHkob2xkX3BhdGgsIG5ld19wYXRoLCBmb2xsb3dfc3ltbGlua3M9RmFsc2UpCiAgICAgICAgICAgICAgICBwcmludChmIlJlbmFtZWQge2ZpbGVuYW1lfSB0byB7bmV3X2ZpbGVuYW1lfSIpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgcHJpbnQoZiLml6Dms5Xor7vlj5bnm67lvZU6IHtlfSIpCgoKZGVmIHNlbGVjdF9mb2xkZXIoKToKICAgICMg5by55Ye65paH5Lu25aS56YCJ5oup5a+56K+d5qGGCiAgICBmb2xkZXJfcGF0aCA9IGZpbGVkaWFsb2cuYXNrZGlyZWN0b3J5KCkKICAgIGlmIGZvbGRlcl9wYXRoOgogICAgICAgIHJlbmFtZV9pbWFnZXMoZm9sZGVyX3BhdGgpCgojIOWIm+W7uuS4u+eql+WPowpyb290ID0gdGsuVGsoKQpyb290LnRpdGxlKCLor7vlj5bmnKzlnLDmlofku7blpLkiKQoKIyDliJvlu7rmjInpkq4KYnV0dG9uID0gdGsuQnV0dG9uKHJvb3QsIHRleHQ9IumAieaLqeaWh+S7tuWkuSIsIGNvbW1hbmQ9c2VsZWN0X2ZvbGRlcikKYnV0dG9uLnBhY2socGFkeT0yMCkKCiMg6L+Q6KGM5Li75b6q546vCnJvb3QubWFpbmxvb3AoKQpgYGA="
);
console.log(decode(text.value));
</script>
<style scoped lang="scss"></style>
